/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.46
 * Generated at: 2017-10-30 01:17:19 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.views.accom;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import accom.model.vo.Accommodation;
import accom.model.vo.Room;
import accom.model.vo.AccomReview;
import java.util.*;
import java.sql.Date;
import member.model.vo.Member;

public final class accomDetailView_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/views/accom/../includes/footer.jsp", Long.valueOf(1509323787349L));
    _jspx_dependants.put("/views/accom/../includes/header.jsp", Long.valueOf(1509323787350L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("accom.model.vo.Room");
    _jspx_imports_classes.add("accom.model.vo.Accommodation");
    _jspx_imports_classes.add("member.model.vo.Member");
    _jspx_imports_classes.add("accom.model.vo.AccomReview");
    _jspx_imports_classes.add("java.sql.Date");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");

   Accommodation accom = (Accommodation)request.getAttribute("accom");
   ArrayList<Room> list = (ArrayList<Room>)request.getAttribute("list");
   ArrayList<AccomReview> areviewList = (ArrayList<AccomReview>) request.getAttribute("areviewList");
   double gradeAvg = Double.parseDouble(String.valueOf(request.getAttribute("gradeAvg")));
   int currentPage = ((Integer)request.getAttribute("currentPage")).intValue();

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\"\r\n");
      out.write("   href=\"/tonight/css/bootstrap.min.css\">\r\n");
      out.write("</head>\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("\r\n");
      out.write(".jumbotron {\r\n");
      out.write("      margin-bottom: 0px;\r\n");
      out.write("       background-image: url(img/loginbackground.jpg);\r\n");
      out.write("       background-position: 0% 25%;\r\n");
      out.write("       background-size: cover;\r\n");
      out.write("       background-repeat: no-repeat;\r\n");
      out.write("       color: white !important;\r\n");
      out.write("       height: 20px;\r\n");
      out.write("   }\r\n");
      out.write("\r\n");
      out.write(".container {\r\n");
      out.write("   padding: 80px 60px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".person {\r\n");
      out.write("   border: 10px solid transparent;\r\n");
      out.write("   margin-bottom: 25px;\r\n");
      out.write("   width: 80%;\r\n");
      out.write("   height: 80%;\r\n");
      out.write("   opacity: 0.7;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".person:hover {\r\n");
      out.write("   border-color: #f1f1f1;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".carousel-inner img {\r\n");
      out.write("   -webkit-filter: grayscale(90%);\r\n");
      out.write("   filter: grayscale(90%); /* make all photos black and white */\r\n");
      out.write("   width: 100%; /* Set width to 100% */\r\n");
      out.write("   margin: auto;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".carousel-caption h3 {\r\n");
      out.write("   color: #fff !important;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("@media ( max-width : 600px) {\r\n");
      out.write("   .carousel-caption {\r\n");
      out.write("      display: none;\r\n");
      out.write("      /* Hide the carousel text when the screen is less than 600 pixels wide */\r\n");
      out.write("   }\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/**/\r\n");
      out.write(".box-info.full {\r\n");
      out.write("   padding: 0px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".box-info:hover {\r\n");
      out.write("   color: #393E48;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".box-info {\r\n");
      out.write("   position: relative;\r\n");
      out.write("   padding: 15px;\r\n");
      out.write("   background: #fff;\r\n");
      out.write("   color: #5b5b5b;\r\n");
      out.write("   margin-bottom: 20px;\r\n");
      out.write("   -webkit-transition: All 0.4s ease;\r\n");
      out.write("   -moz-transition: All 0.4s ease;\r\n");
      out.write("   -o-transition: All 0.4s ease;\r\n");
      out.write("   background: #FFFFFF;\r\n");
      out.write("   margin-top: 20px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".box-info .nav-tabs {\r\n");
      out.write("   background: #1B1E24;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".box-info .nav-tabs  li.active  a, .box-info .nav-tabs  li.active  a:hover,\r\n");
      out.write("   .box-info .nav-tabs  li.active  a:focus {\r\n");
      out.write("   cursor: default;\r\n");
      out.write("   border-top: none;\r\n");
      out.write("   border-right: none;\r\n");
      out.write("   border-left: none;\r\n");
      out.write("   border-bottom: none;\r\n");
      out.write("   background-color: #ffffff;\r\n");
      out.write("   color: #1B1E24;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".box-info .nav-tabs  li.active  a i, .box-info .nav-tabs  li.active  a:hover i,\r\n");
      out.write("   .box-info .nav-tabs  li.active  a:focus i {\r\n");
      out.write("   color: #212121;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".box-info .nav-tabs  li  a i {\r\n");
      out.write("   color: #fff;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".box-info.full .box-footer {\r\n");
      out.write("   padding: 20px 20px 15px 20px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".box-info .media-list {\r\n");
      out.write("   margin-top: 30px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".box-info .media-list .media {\r\n");
      out.write("   padding: 5px 20px;\r\n");
      out.write("   border-bottom: 1px solid #eaeaea;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".box-info .media-list .media .media-object {\r\n");
      out.write("   width: 50px;\r\n");
      out.write("}\r\n");
      out.write(".scroll-widget{\r\n");
      out.write("    overflow: hidden;\r\n");
      out.write("    width: auto;\r\n");
      out.write("}    \r\n");
      out.write("</style>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("function delete_event() {\r\n");
      out.write("\tif(confirm(\"정말 삭제하시겠습니까?\") == true) {\r\n");
      out.write("\t\tlocation.href='/tonight/adelete?anum=");
      out.print(accom.getAccId());
      out.write("';\r\n");
      out.write("\t}\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("<body>\r\n");
      out.write('\r');
      out.write('\n');
 Member member = (Member)session.getAttribute("member"); 
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"ko\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"/tonight/css/bootstrap.min.css\">\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("\t.navbar {\r\n");
      out.write("\t\tbackground-color: transparent;\r\n");
      out.write("\t\tborder-color: transparent;\r\n");
      out.write("\t}\r\n");
      out.write("\t.navbar:hover {\r\n");
      out.write("\t\tbackground-color: black !important;\r\n");
      out.write("\t}\r\n");
      out.write("\t.navbar a {\r\n");
      out.write("\t    color: white !important;\r\n");
      out.write("\t}\r\n");
      out.write("\t.navbar a:hover { color: red !important; }\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t@media (min-width: 768px) {\r\n");
      out.write("\t  .navbar-nav.navbar-center {\r\n");
      out.write("\t    position: absolute;\r\n");
      out.write("\t    left: 50%;\r\n");
      out.write("\t    transform: translatex(-50%);\r\n");
      out.write("\t  }\r\n");
      out.write("\t  #mobile-logo {\r\n");
      out.write("\t  \tdisplay: none !important;\r\n");
      out.write("\t  \tvisibility: hidden !important;\r\n");
      out.write("\t  }\r\n");
      out.write("\t}\r\n");
      out.write("\t@media (max-width: 767px) {\r\n");
      out.write("\t  #logo {\r\n");
      out.write("\t  \tdisplay: none !important;\r\n");
      out.write("\t  \tvisibility: hidden !important;\r\n");
      out.write("\t  }\r\n");
      out.write("\t  \r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<nav class=\"navbar navbar-default navbar-fixed-top\">\r\n");
      out.write("  <div class=\"container-fluid\">\r\n");
      out.write("    <div class=\"navbar-header\">\r\n");
      out.write("      <button type=\"button\" class=\"navbar-toggle\" data-toggle=\"collapse\" data-target=\".navbar-collapse\">\r\n");
      out.write("        <span class=\"icon-bar\"></span>\r\n");
      out.write("        <span class=\"icon-bar\"></span>\r\n");
      out.write("        <span class=\"icon-bar\"></span>                        \r\n");
      out.write("      </button>\r\n");
      out.write("      <a class=\"navbar-brand\" id=\"mobile-logo\"href=\"/tonight/index.jsp\"><img width=\"30\" src=\"/tonight/img/logo.png\"></a>\r\n");
      out.write("    </div>\r\n");
      out.write("    \r\n");
      out.write("    <div class=\"collapse navbar-collapse\">\r\n");
      out.write("      <ul class=\"nav navbar-nav navbar-center\">\r\n");
      out.write("        <li><a href=\"#\">인기</a></li>\r\n");
      out.write("        <li><a href=\"/tonight/tlist\">여행&nbsp;&nbsp;&nbsp;&nbsp;</a></li>\r\n");
      out.write("        <li><a id=\"logo\" class=\"navbar-brand\" href=\"/tonight/index.jsp\"><img width=\"65\" src=\"/tonight/img/logo.png\"></a>\r\n");
      out.write("        <li><a href=\"/tonight/alist\">숙소</a></li>\r\n");
      out.write("        <li><a href=\"/tonight/views/customerservice/serviceListView.jsp\">고객센터</a></li>\r\n");
      out.write("      </ul>\r\n");
      out.write("      <ul class=\"nav navbar-nav navbar-right\">\r\n");
      out.write("      \t");
 if(member == null) { 
      out.write("\r\n");
      out.write("        \t<li><a href=\"/tonight/views/member/loginForm.jsp\">로그인&nbsp;&nbsp;</a></li>\r\n");
      out.write("        ");
 } else { 
      out.write("\r\n");
      out.write("        \t<li><a href=\"minfo?memberid=");
      out.print( member.getMemberId() );
      out.write("\">마이페이지</a></li>\r\n");
      out.write("        \t<li><a href=\"/tonight/logout\">로그아웃&nbsp;&nbsp;</a></li>\r\n");
      out.write("        ");
 } 
      out.write("\r\n");
      out.write("        </ul>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("</nav>\r\n");
      out.write("<div id=\"startchange\"></div>\r\n");
      out.write("\r\n");
      out.write("<script src=\"/tonight/js/jquery-3.2.1.min.js\"></script>\r\n");
      out.write("<script src=\"/tonight/js/bootstrap.min.js\"></script>\r\n");
      out.write("<script>\r\n");
      out.write("\t$(function(){\r\n");
      out.write("\t\tvar scroll_start = 0;\r\n");
      out.write("\t\tvar startchange = $('#startchange');\r\n");
      out.write("\t\tvar offset = startchange.offset();\r\n");
      out.write("\r\n");
      out.write("\t\tif (startchange.length){\r\n");
      out.write("\t\t\t$(document).scroll(function() { \r\n");
      out.write("\t\t\t\tscroll_start = $(this).scrollTop();\r\n");
      out.write("\t\t\t\tif(scroll_start > offset.top) {\r\n");
      out.write("\t\t\t\t\t$('.navbar').css('background-color', 'rgba(0, 0, 0, 0.7)');\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\telse {\r\n");
      out.write("\t\t\t\t\t$('.navbar').css('background-color', 'transparent');\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t}\r\n");
      out.write("\t});\r\n");
      out.write("</script>\r\n");
      out.write("<script src=\"/tonight/js/jquery-3.2.1.min.js\"></script>\r\n");
      out.write("<script src=\"/tonight/js/bootstrap.min.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("<div class=\"jumbotron\">\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("   <div class=\"container\" id=\"toTop\">\r\n");
      out.write("      <h3 class=\"text-center\">");
      out.print(accom.getAccName());
      out.write("</h3>\r\n");
      out.write("      <br>\r\n");
      out.write("      <div class=\"row\">\r\n");
      out.write("   \r\n");
      out.write("         <div id=\"myCarousel\" class=\"carousel slide col-md-8\" data-ride=\"carousel\"><!-- 이미지슬라이더 -->\r\n");
      out.write("            <!-- Indicators -->\r\n");
      out.write("            <ol class=\"carousel-indicators\">\r\n");
      out.write("               <li data-target=\"#myCarousel\" data-slide-to=\"0\" class=\"active\"></li>\r\n");
      out.write("               <li data-target=\"#myCarousel\" data-slide-to=\"1\"></li>\r\n");
      out.write("               <li data-target=\"#myCarousel\" data-slide-to=\"2\"></li>\r\n");
      out.write("            </ol>\r\n");
      out.write("\r\n");
      out.write("            <!-- Wrapper for slides -->\r\n");
      out.write("            <div class=\"carousel-inner\">\r\n");
      out.write("               <div class=\"item active\">\r\n");
      out.write("                  <img src=\"/tonight/uploadfiles/la.jpg\" alt=\"Los Angeles\" style=\"width: 100%;\">\r\n");
      out.write("                  <div class=\"carousel-caption\">\r\n");
      out.write("                     <h3>New York</h3>\r\n");
      out.write("                     <p>The atmosphere in New York is lorem ipsum.</p>\r\n");
      out.write("                  </div>\r\n");
      out.write("               </div>\r\n");
      out.write("\r\n");
      out.write("               <div class=\"item\">\r\n");
      out.write("                  <img src=\"/tonight/uploadfiles/chicago.jpg\" alt=\"Chicago\" style=\"width: 100%;\">\r\n");
      out.write("                  <div class=\"carousel-caption\">\r\n");
      out.write("                     <h3>Chicago</h3>\r\n");
      out.write("                     <p>Thank you, Chicago - A night we won't forget.</p>\r\n");
      out.write("                  </div>\r\n");
      out.write("               </div>\r\n");
      out.write("\r\n");
      out.write("               <div class=\"item\">\r\n");
      out.write("                  <img src=\"/tonight/uploadfiles/ny.jpg\" alt=\"New york\" style=\"width: 100%;\">\r\n");
      out.write("                  <div class=\"carousel-caption\">\r\n");
      out.write("                     <h3>LA</h3>\r\n");
      out.write("                     <p>Even though the traffic was a mess, we had the best time\r\n");
      out.write("                        playing at Venice Beach!</p>\r\n");
      out.write("                  </div>\r\n");
      out.write("               </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("               <!-- Left and right controls -->\r\n");
      out.write("               <a class=\"left carousel-control\" href=\"#myCarousel\" data-slide=\"prev\"> \r\n");
      out.write("               <span class=\"glyphicon glyphicon-chevron-left\"></span> <span class=\"sr-only\">Previous</span>\r\n");
      out.write("               </a> <a class=\"right carousel-control\" href=\"#myCarousel\" data-slide=\"next\">\r\n");
      out.write("               <span class=\"glyphicon glyphicon-chevron-right\"></span> <span class=\"sr-only\">Next</span>\r\n");
      out.write("               </a>\r\n");
      out.write("            </div>\r\n");
      out.write("         </div><!-- end 이미지슬라이더 -->\r\n");
      out.write("         <div class=\"col-md-4\">\r\n");
      out.write("            <hr>\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("               <div class=\"col-xs-4\">\r\n");
      out.write("                  <p>숙소 주소</p>\r\n");
      out.write("               </div>\r\n");
      out.write("               <div id=\"map\" style=\"height:350px; width:auto;\">\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <hr>\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("               <div class=\"col-xs-4\">\r\n");
      out.write("                  <p>숙소 등급</p>\r\n");
      out.write("               </div>\r\n");
      out.write("               <div class=\"col-xs-8\">\r\n");
      out.write("                  <p>");
      out.print(accom.getAccRank());
      out.write("</p>\r\n");
      out.write("               </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <hr>\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("               <div class=\"col-xs-4\">\r\n");
      out.write("                  <p>연락처</p>\r\n");
      out.write("               </div>\r\n");
      out.write("               <div class=\"col-xs-8\">\r\n");
      out.write("                  <p>");
      out.print(accom.getAccContact());
      out.write("</p>\r\n");
      out.write("               </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <hr>   \r\n");
      out.write("         <div class=\"row\">\r\n");
      out.write("\r\n");
      out.write("               <div class=\"col-xs-4\">\r\n");
      out.write("                  <a href=\"#\"> <img src=\"/tonight/uploadfiles/bandmember.jpg\"\r\n");
      out.write("                     class=\"img-circle person\" alt=\"Random Name\"></a>\r\n");
      out.write("\r\n");
      out.write("               </div>\r\n");
      out.write("               <div class=\"col-xs-8\">\r\n");
      out.write("                  <p></p>\r\n");
      out.write("                  <p>사업자 소개글 공간 입니다</p>\r\n");
      out.write("                  <button>쪽지남기기</button>\r\n");
      out.write("               </div>\r\n");
      out.write("               <hr>\r\n");
      out.write("               <div class=\"col-xs-12\">\r\n");
      out.write("               ");
  if(member != null){ 
      out.write("\r\n");
      out.write("\t\t\t   ");
 if(member.getMemberId().equals(accom.getBizId())) { 
      out.write("\r\n");
      out.write("\t\t\t   <div align=\"center\">\r\n");
      out.write("\t\t\t   <a class=\"btn btn-default\" role=\"button\" href=\"/tonight/aupview?anum=");
      out.print(accom.getAccId());
      out.write("\">수정하기</a>\r\n");
      out.write("\t\t\t\t&nbsp; \r\n");
      out.write("\t\t\t   <a class=\"btn btn-default\" role=\"button\" onclick=\"delete_event();\">삭제하기</a>\r\n");
      out.write("\t\t\t   </div>\r\n");
      out.write("\t\t\t\t");
  }} 
      out.write("\r\n");
      out.write("               </div>\r\n");
      out.write("               \r\n");
      out.write("               \r\n");
      out.write("            </div>\r\n");
      out.write("            <hr>\r\n");
      out.write("         </div>\r\n");
      out.write("      </div><!-- end <div class=\"row\">  -->\r\n");
      out.write("   </div><!-- end <div class=\"container\" id=\"toTop\"> -->\r\n");
      out.write("   <div class=\"container\">\r\n");
      out.write("      <div class=\"row\">\r\n");
      out.write("         <div class=\"col-md-8\">\r\n");
      out.write("            <div class=\"panel panel-default\">\r\n");
      out.write("               <div class=\"panel-heading\">달력 공간</div>\r\n");
      out.write("               <div class=\"panel-body\">\r\n");
      out.write("\t                  <img src=\"https://placehold.it/150x80?text=IMAGE\"\r\n");
      out.write("\t                     class=\"img-responsive\" style=\"width: 50%\" alt=\"Image\">\r\n");
      out.write("\t                     <br>\r\n");
      out.write("\t\t\t                   <table class=\"table table-hover\">\r\n");
      out.write("\t\t\t                   <tr><th>객실명</th><th>성인가격</th><th>소인가격</th><th>할인율</th><th>객실 예약상태</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t   <th>상세정보</th></tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t");

										for(Room r : list){
									
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<tr height=\"30\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td>");
      out.print( r.getRoomName() );
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td>");
      out.print( r.getAdult_Price() );
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td>");
      out.print( r.getChild_Price() );
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td>");
      out.print( r.getDiscount() );
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td>");
      out.print( r.getRoomState() );
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td>");
      out.print( r.getRoomDetails() );
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<!--<input type=\"radio\" name=\"test\" value=\"1\" onclick=\"chk()\">상세보기\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<input type=\"radio\" name=\"test\" value=\"2\" onclick=\"chk()\">접기 -->\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t");
  } 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</table>\r\n");
      out.write("                  ");
      out.write("\r\n");
      out.write("                  \r\n");
      out.write("               </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"panel panel-default hidden-md hidden-lg\">\r\n");
      out.write("               <div class=\"panel-heading\">선택 확인/예약 공간</div>\r\n");
      out.write("               <div class=\"panel-body\">\r\n");
      out.write("                  <img src=\"https://placehold.it/150x80?text=IMAGE\"\r\n");
      out.write("                     class=\"img-responsive\" style=\"width: 100%\" alt=\"Image\">\r\n");
      out.write("               </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"panel panel-default\">\r\n");
      out.write("               <div class=\"panel-heading\">숙소상세정보</div>\r\n");
      out.write("               <div class=\"panel-body\">\r\n");
      out.write("                  ");
      out.print(accom.getAccInfo());
      out.write("\r\n");
      out.write("               </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"panel panel-default\">\r\n");
      out.write("               <div class=\"panel-heading\">지도</div>\r\n");
      out.write("               <div class=\"panel-body\">\r\n");
      out.write("                  ");
      out.print(accom.getAccAddress());
      out.write("\r\n");
      out.write("                 \r\n");
      out.write("\t\t\t\t\t    \r\n");
      out.write("               </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"panel panel-default\">\r\n");
      out.write("               <div class=\"panel-heading\">이용규칙</div>\r\n");
      out.write("               <div class=\"panel-body\">\r\n");
      out.write("                  ");
      out.print(accom.getAccRules() );
      out.write("\r\n");
      out.write("               </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"panel panel-default\">\r\n");
      out.write("               <div class=\"panel-heading\">편의시설</div>\r\n");
      out.write("               <div class=\"panel-body\">\r\n");
      out.write("                  ");
      out.write("\r\n");
      out.write("                  ");
 
                  String[] facilitiess = accom.getFacilities().split(",");
                  boolean[] checked = new boolean[9];
                  for(int i = 0; i < facilitiess.length; i++) {
                	  if(facilitiess[i].equals("주차장"))
                		  checked[0] = true;
                      if(facilitiess[i].equals("수영장"))
                    	  checked[1] = true;
                      if(facilitiess[i].equals("엘레베이터"))
                    	  checked[2] = true;
                      if(facilitiess[i].equals("무선인터넷"))
                    	  checked[3] = true;
                      if(facilitiess[i].equals("부엌"))
                    	  checked[4] = true;
                      if(facilitiess[i].equals("욕조"))
                    	  checked[5] = true;
                      if(facilitiess[i].equals("에어컨"))
                    	  checked[6] = true;
                      if(facilitiess[i].equals("세탁기"))
                    	  checked[7] = true;
                      if(facilitiess[i].equals("TV"))
                    	  checked[8] = true;
                  }
                  
      out.write("\r\n");
      out.write("                  \r\n");
      out.write("                  <table width=\"100%\">\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t");
	if(checked[0] == true){ 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<td><input type=\"checkbox\" name=\"afacilities\" value=\"주차장\" checked> 주차장</td>\r\n");
      out.write("\t\t\t\t\t\t");
  }else{  
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<td><input type=\"checkbox\" name=\"afacilities\" value=\"주차장\"> 주차장</td>\t\r\n");
      out.write("\t\t\t\t\t\t");
  } 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t");
	if(checked[1] == true){ 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<td><input type=\"checkbox\" name=\"afacilities\" value=\"수영장\" checked> 수영장</td>\r\n");
      out.write("\t\t\t\t\t\t");
  }else{  
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<td><input type=\"checkbox\" name=\"afacilities\" value=\"수영장\"> 수영장</td>\r\n");
      out.write("\t\t\t\t\t\t");
  } 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t");
	if(checked[2] == true){ 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<td><input type=\"checkbox\" name=\"afacilities\" value=\"엘레베이터\" checked> 엘레베이터</td>\r\n");
      out.write("\t\t\t\t\t\t");
  }else{  
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<td><input type=\"checkbox\" name=\"afacilities\" value=\"엘레베이터\"> 엘레베이터</td>\r\n");
      out.write("\t\t\t\t\t\t");
  } 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t");
	if(checked[3] == true){ 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<td><input type=\"checkbox\" name=\"afacilities\" value=\"무선인터넷\" checked> 무선인터넷</td>\r\n");
      out.write("\t\t\t\t\t\t");
  }else{  
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<td><input type=\"checkbox\" name=\"afacilities\" value=\"무선인터넷\" > 무선인터넷</td>\r\n");
      out.write("\t\t\t\t\t\t");
  } 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t");
	if(checked[4] == true){ 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<td><input type=\"checkbox\" name=\"afacilities\" value=\"부엌\" checked> 부엌</td>\r\n");
      out.write("\t\t\t\t\t\t");
  }else{  
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<td><input type=\"checkbox\" name=\"afacilities\" value=\"부엌\" > 부엌</td>\r\n");
      out.write("\t\t\t\t\t\t");
  } 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t");
	if(checked[5] == true){ 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<td><input type=\"checkbox\" name=\"afacilities\" value=\"욕조\" checked> 욕조</td>\r\n");
      out.write("\t\t\t\t\t\t");
  }else{  
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<td><input type=\"checkbox\" name=\"afacilities\" value=\"욕조\" > 욕조</td>\r\n");
      out.write("\t\t\t\t\t\t");
  } 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t");
	if(checked[6] == true){ 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<td><input type=\"checkbox\" name=\"afacilities\" value=\"에어컨\" checked> 에어컨</td>\r\n");
      out.write("\t\t\t\t\t\t");
  }else{  
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<td><input type=\"checkbox\" name=\"afacilities\" value=\"에어컨\" > 에어컨</td>\r\n");
      out.write("\t\t\t\t\t\t");
  } 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t");
	if(checked[7] == true){ 
      out.write("\t\r\n");
      out.write("\t\t\t\t\t\t<td><input type=\"checkbox\" name=\"afacilities\" value=\"세탁기\" checked> 세탁기</td>\r\n");
      out.write("\t\t\t\t\t\t");
  }else{  
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<td><input type=\"checkbox\" name=\"afacilities\" value=\"세탁기\" > 세탁기</td>\r\n");
      out.write("\t\t\t\t\t\t");
  } 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t");
	if(checked[8] == true){ 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<td><input type=\"checkbox\" name=\"afacilities\" value=\"TV\" checked> TV</td>\r\n");
      out.write("\t\t\t\t\t\t");
  }else{  
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<td><input type=\"checkbox\" name=\"afacilities\" value=\"TV\" > TV</td>\r\n");
      out.write("\t\t\t\t\t\t");
  } 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t</table>\r\n");
      out.write("               </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"panel panel-default\">\r\n");
      out.write("               <div class=\"panel-heading\">환불규정</div>\r\n");
      out.write("               <div class=\"panel-body\">\r\n");
      out.write("                  ");
      out.print(accom.getAccRefund());
      out.write("\r\n");
      out.write("               </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"panel panel-default\">\r\n");
      out.write("               <div class=\"panel-heading\">후기\r\n");
      out.write("                 ");
 if(areviewList.size() > 0) {
      out.write("\r\n");
      out.write("                     <p class=\"pull-right\">(");
      out.print( areviewList.size() );
      out.write(")</p>\r\n");
      out.write("                     <p class=\"pull-right\">");
      out.print( gradeAvg );
      out.write("</p>\r\n");
      out.write("                     <img src=\"/tonight/img/starGrade");
      out.print( Math.round(gradeAvg) );
      out.write(".png\" class=\"col-xs-3 pull-right\" style=\"margin-top:-10px\">\r\n");
      out.write("                  ");
 } 
      out.write("\r\n");
      out.write("               </div>\r\n");
      out.write("               <div class=\"panel-body box-info\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<div class=\"tab-pane active animated fadeInRight\" id=\"comments\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"scroll-widget\">\r\n");
      out.write("\t\t\t\t\t\t\t<ul class=\"media-list\">\r\n");
      out.write("\t\t\t\t\t\t\t");
 if (areviewList.isEmpty()) {	
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<li class=\"media\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<p>후기가 없습니다.</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t");
 } else if(areviewList.size() < 4){ 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t");
 for (AccomReview areview : areviewList) { 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li class=\"media\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<a class=\"pull-left\" href=\"#fakelink\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<img class=\"media-object\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tsrc=\"https://bootdey.com/img/Content/User_for_snippets.png\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\talt=\"Avatar\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"media-body\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<h4 class=\"media-heading\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<a href=\"#fakelink\">");
      out.print(areview.getArWriterId() );
      out.write("</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<small>");
      out.print(areview.getArGrade() );
      out.write("</small>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</h4>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<img src=\"/tonight/img/starGrade");
      out.print( Math.round(areview.getArGrade()) );
      out.write(".png\" class=\"col-xs-3\" style=\"margin-top:-10px\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"col-xs-9\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<p>");
      out.print(areview.getArContent() );
      out.write("</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<p></p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t");
 } 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t");
 } else {
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t");
 for (int i=0; i < 3; i++) { 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li class=\"media\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<a class=\"pull-left\" href=\"#fakelink\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<img class=\"media-object\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tsrc=\"https://bootdey.com/img/Content/User_for_snippets.png\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\talt=\"Avatar\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"media-body\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<h4 class=\"media-heading\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<a href=\"#fakelink\">");
      out.print( areviewList.get(i).getArWriterId() );
      out.write("</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<small>");
      out.print(areviewList.get(i).getArDate() );
      out.write("</small>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<small>grade ");
      out.print(areviewList.get(i).getArGrade() );
      out.write("</small>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</h4>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<img src=\"/tonight/img/starGrade");
      out.print( Math.round(areviewList.get(i).getArGrade()) );
      out.write(".png\" class=\"col-xs-3\" style=\"margin-top:-10px\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"col-xs-9\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<p>");
      out.print( areviewList.get(i).getArContent() );
      out.write("</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t");
 } 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<li class=\"media\"><a data-toggle=\"modal\" data-target=\"#addReview\">");
      out.print( areviewList.size()-3 );
      out.write("개 더보기..</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t");
 } 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("         <div class=\"col-md-4 hidden-sm hidden-xs\">\r\n");
      out.write("            <div class=\"panel panel-default panel-affix\" id=\"myScrollspy\">\r\n");
      out.write("\r\n");
      out.write("               <div class=\"panel-heading\">결제 공간</div>\r\n");
      out.write("               <div class=\"panel-body\">\r\n");
      out.write("                  <div class=\"nav nav-pills nav-stacked\">\r\n");
      out.write("                     <img src=\"https://placehold.it/150x80?text=IMAGE\"\r\n");
      out.write("                        class=\"img-responsive\" style=\"width: 100%\" alt=\"Image\"> <a\r\n");
      out.write("                        href=\"#toTop\">Back To Top </a>\r\n");
      out.write("                  </div>\r\n");
      out.write("               </div>\r\n");
      out.write("            </div>\r\n");
      out.write("         </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("      </div>\r\n");
      out.write("   </div>\r\n");
      out.write("   \r\n");
      out.write("<div class=\"modal fade\" id=\"addReview\" role=\"dialog\">\r\n");
      out.write("    <div class=\"modal-dialog\">\r\n");
      out.write("    \r\n");
      out.write("     <!-- Modal content-->\r\n");
      out.write("      <div class=\"modal-content\">\r\n");
      out.write("        <div class=\"modal-header\">\r\n");
      out.write("        <button type=\"button\" class=\"close\" data-dismiss=\"modal\">&times;</button>\r\n");
      out.write("          <h4 class=\"modal-title\">후기</h4>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"modal-body box-info\">\r\n");
      out.write("           <div class=\"tab-pane active animated fadeInRight\" id=\"comments\">\r\n");
      out.write("            <div class=\"scroll-widget\">\r\n");
      out.write("               <ul class=\"media-list\">\r\n");
      out.write("                  ");
 for (AccomReview areview : areviewList) { 
      out.write("\r\n");
      out.write("                     <li class=\"media\">\r\n");
      out.write("                        <a class=\"pull-left\" href=\"#fakelink\">\r\n");
      out.write("                              <img class=\"media-object\"\r\n");
      out.write("                              src=\"https://bootdey.com/img/Content/User_for_snippets.png\"\r\n");
      out.write("                              alt=\"Avatar\">\r\n");
      out.write("                        </a>\r\n");
      out.write("                        <div class=\"media-body\">\r\n");
      out.write("                              <h4 class=\"media-heading\">\r\n");
      out.write("                                 <a href=\"#fakelink\">");
      out.print(areview.getArWriterId() );
      out.write("</a>\r\n");
      out.write("                                 <small>");
      out.print(areview.getArDate() );
      out.write("</small>\r\n");
      out.write("                              </h4>\r\n");
      out.write("                              <div class=\"row\">\r\n");
      out.write("                                 <img src=\"/tonight/img/starGrade");
      out.print( Math.round(areview.getArGrade()) );
      out.write(".png\" class=\"col-xs-3\" style=\"margin-top:-10px\">\r\n");
      out.write("                                 <div class=\"col-xs-9\"></div>\r\n");
      out.write("                              </div>\r\n");
      out.write("                              <p>");
      out.print(areview.getArContent() );
      out.write("</p>\r\n");
      out.write("                           </div>\r\n");
      out.write("                        <p></p>\r\n");
      out.write("                     </li>\r\n");
      out.write("                  ");
 } 
      out.write("\r\n");
      out.write("               </ul>\r\n");
      out.write("            </div>\r\n");
      out.write("         </div>\r\n");
      out.write("        </div>\r\n");
      out.write("           <div class=\"modal-footer\">\r\n");
      out.write("            <button type=\"button\" class=\"btn btn-default\" data-dismiss=\"modal\">닫기</button>\r\n");
      out.write("         </div>\r\n");
      out.write("      </div>\r\n");
      out.write("      \r\n");
      out.write("   </div>\r\n");
      out.write("</div> \r\n");
      out.write("<div id=\"fake-footer\"></div>\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"/tonight/css/style.css\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<footer class=\"container-fluid text-center\">\r\n");
      out.write("\t<address>tonight</address>\r\n");
      out.write("\t<small>ⓒ  Gangnam Station Exit 10</small>\r\n");
      out.write("</footer>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("<script src=\"/tonight/js/jquery-3.2.1.min.js\"></script>\r\n");
      out.write("<script src=\"/tonight/js/bootstrap.min.js\"></script>\r\n");
      out.write("<script>\r\n");
      out.write("\t$(function() {\r\n");
      out.write("\r\n");
      out.write("\t\t// name your elements here\r\n");
      out.write("\t\tvar stickyElement = '.panel-affix', // the element you want to make sticky\r\n");
      out.write("\t\tbottomElement = '#fake-footer'; // the bottom element where you want the sticky element to stop (usually the footer) \r\n");
      out.write("\r\n");
      out.write("\t\t// make sure the element exists on the page before trying to initalize\r\n");
      out.write("\t\tif ($(stickyElement).length) {\r\n");
      out.write("\t\t\t$(stickyElement).each(\r\n");
      out.write("\t\t\t\tfunction() {\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t// let's save some messy code in clean variables\r\n");
      out.write("\t\t\t\t\t// when should we start affixing? (the amount of pixels to the top from the element)\r\n");
      out.write("\t\t\t\t\tvar fromTop = $(this).offset().top,\r\n");
      out.write("\t\t\t\t\t// where is the bottom of the element?\r\n");
      out.write("\t\t\t\t\tfromBottom = $(document).height()\r\n");
      out.write("\t\t\t\t\t\t\t- ($(this).offset().top + $(this)\r\n");
      out.write("\t\t\t\t\t\t\t\t\t.outerHeight()),\r\n");
      out.write("\t\t\t\t\t// where should we stop? (the amount of pixels from the top where the bottom element is)\r\n");
      out.write("\t\t\t\t\t// also add the outer height mismatch to the height of the element to account for padding and borders\r\n");
      out.write("\t\t\t\t\tstopOn = $(document).height()\r\n");
      out.write("\t\t\t\t\t\t\t- ($(bottomElement).offset().top)\r\n");
      out.write("\t\t\t\t\t\t\t+ ($(this).outerHeight() - $(this)\r\n");
      out.write("\t\t\t\t\t\t\t\t\t.height());\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t// if the element doesn't need to get sticky, then skip it so it won't mess up your layout\r\n");
      out.write("\t\t\t\t\tif ((fromBottom - stopOn) > 200) {\r\n");
      out.write("\t\t\t\t\t\t// let's put a sticky width on the element and assign it to the top\r\n");
      out.write("\t\t\t\t\t\t$(this).css('width', $(this).width())\r\n");
      out.write("\t\t\t\t\t\t\t\t.css('top', 0).css('position',\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t'');\r\n");
      out.write("\t\t\t\t\t\t// assign the affix to the element\r\n");
      out.write("\t\t\t\t\t\t$(this)\r\n");
      out.write("\t\t\t\t\t\t\t\t.affix({\r\n");
      out.write("\t\t\t\t\t\t\t\t\toffset : {\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t// make it stick where the top pixel of the element is\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\ttop : fromTop - 80,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t// make it stop where the top pixel of the bottom element is\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tbottom : stopOn\r\n");
      out.write("\t\t\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t\t// when the affix get's called then make sure the position is the default (fixed) and it's at the top\r\n");
      out.write("\t\t\t\t\t\t\t\t})\r\n");
      out.write("\t\t\t\t\t\t\t\t.on(\r\n");
      out.write("\t\t\t\t\t\t\t\t\t'affix.bs.affix',\r\n");
      out.write("\t\t\t\t\t\t\t\t\tfunction() {\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t$(this)\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t.css('top',\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t'80px')\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t.css(\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t'position',\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t'');\r\n");
      out.write("\t\t\t\t\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t// trigger the scroll event so it always activates \r\n");
      out.write("\t\t\t\t\t$(window).trigger('scroll');\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write("\t});\r\n");
      out.write("</script>\r\n");
      out.write("<script>\r\n");
      out.write("var mapContainer = document.getElementById('map'), // 지도를 표시할 div \r\n");
      out.write("mapOption = {\r\n");
      out.write("    center: new daum.maps.LatLng(33.450701, 126.570667), // 지도의 중심좌표\r\n");
      out.write("    level: 3 // 지도의 확대 레벨\r\n");
      out.write("};  \r\n");
      out.write("\r\n");
      out.write("//지도를 생성합니다    \r\n");
      out.write("var map = new daum.maps.Map(mapContainer, mapOption); \r\n");
      out.write("\r\n");
      out.write("//지도 타입 변경 컨트롤을 생성한다\r\n");
      out.write("var mapTypeControl = new daum.maps.MapTypeControl();\r\n");
      out.write("\r\n");
      out.write("// 지도의 상단 우측에 지도 타입 변경 컨트롤을 추가한다\r\n");
      out.write("map.addControl(mapTypeControl, daum.maps.ControlPosition.TOPRIGHT);\t\r\n");
      out.write("\r\n");
      out.write("// 지도에 확대 축소 컨트롤을 생성한다\r\n");
      out.write("var zoomControl = new daum.maps.ZoomControl();\r\n");
      out.write("\r\n");
      out.write("// 지도의 우측에 확대 축소 컨트롤을 추가한다\r\n");
      out.write("map.addControl(zoomControl, daum.maps.ControlPosition.RIGHT);\r\n");
      out.write("\r\n");
      out.write("//주소-좌표 변환 객체를 생성합니다\r\n");
      out.write("var geocoder = new daum.maps.services.Geocoder();\r\n");
      out.write("\r\n");
      out.write("//주소로 좌표를 검색합니다\r\n");
      out.write("geocoder.addressSearch('");
      out.print(accom.getAccAddress() );
      out.write("', function(result, status) {\r\n");
      out.write("\r\n");
      out.write("// 정상적으로 검색이 완료됐으면 \r\n");
      out.write(" if (status === daum.maps.services.Status.OK) {\r\n");
      out.write("\r\n");
      out.write("    var coords = new daum.maps.LatLng(result[0].y, result[0].x);\r\n");
      out.write("\r\n");
      out.write("    // 결과값으로 받은 위치를 마커로 표시합니다\r\n");
      out.write("    var marker = new daum.maps.Marker({\r\n");
      out.write("        map: map,\r\n");
      out.write("        position: coords\r\n");
      out.write("    });\r\n");
      out.write("\r\n");
      out.write("    // 인포윈도우로 장소에 대한 설명을 표시합니다\r\n");
      out.write("    var infowindow = new daum.maps.InfoWindow({\r\n");
      out.write("        content: '<div style=\"width:150px;text-align:center;padding:6px 0;\">숙소위치</div>'\r\n");
      out.write("    });\r\n");
      out.write("    infowindow.open(map, marker);\r\n");
      out.write("\r\n");
      out.write("    // 지도의 중심을 결과값으로 받은 위치로 이동시킵니다\r\n");
      out.write("    map.setCenter(coords);\r\n");
      out.write("} \r\n");
      out.write("});    \r\n");
      out.write("</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
