/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.46
 * Generated at: 2017-10-25 02:06:35 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.views.tour;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.ArrayList;
import tour.model.vo.Tour;
import tour.model.vo.TourDetail;
import tour.model.vo.TourReview;
import tour.model.vo.TourConf;
import member.model.vo.Member;

public final class tourDetailView_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/views/tour/../includes/footer.jsp", Long.valueOf(1508895001737L));
    _jspx_dependants.put("/views/tour/../includes/header.jsp", Long.valueOf(1508895001740L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("tour.model.vo.TourConf");
    _jspx_imports_classes.add("member.model.vo.Member");
    _jspx_imports_classes.add("tour.model.vo.TourReview");
    _jspx_imports_classes.add("tour.model.vo.Tour");
    _jspx_imports_classes.add("tour.model.vo.TourDetail");
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');

	Tour tour = (Tour) request.getAttribute("tour");
	TourDetail tdetail = (TourDetail) request.getAttribute("tdetail");
	ArrayList<TourReview> treviewList = (ArrayList<TourReview>) request.getAttribute("treviewList");
	double gradeAvg = Double.parseDouble(String.valueOf(request.getAttribute("gradeAvg")));
	ArrayList<TourConf> tconfList = (ArrayList<TourConf>) request.getAttribute("tconfList");

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"ko\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\"\r\n");
      out.write("\thref=\"/tonight/css/bootstrap.min.css\">\r\n");
      out.write("</head>\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("\r\n");
      out.write(".jumbotron {\r\n");
      out.write("\t\tmargin-bottom: 0px;\r\n");
      out.write("\t    background-image: url(img/loginbackground.jpg);\r\n");
      out.write("\t    background-position: 0% 25%;\r\n");
      out.write("\t    background-size: cover;\r\n");
      out.write("\t    background-repeat: no-repeat;\r\n");
      out.write("\t    color: white !important;\r\n");
      out.write("\t    height: 20px;\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write(".container {\r\n");
      out.write("\tpadding: 80px 60px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".person {\r\n");
      out.write("\tborder: 10px solid transparent;\r\n");
      out.write("\tmargin-bottom: 25px;\r\n");
      out.write("\twidth: 80%;\r\n");
      out.write("\theight: 80%;\r\n");
      out.write("\topacity: 0.7;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".person:hover {\r\n");
      out.write("\tborder-color: #f1f1f1;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".carousel-inner img {\r\n");
      out.write("\t-webkit-filter: grayscale(90%);\r\n");
      out.write("\tfilter: grayscale(90%); /* make all photos black and white */\r\n");
      out.write("\twidth: 100%; /* Set width to 100% */\r\n");
      out.write("\tmargin: auto;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".carousel-caption h3 {\r\n");
      out.write("\tcolor: #fff !important;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("@media ( max-width : 600px) {\r\n");
      out.write("\t.carousel-caption {\r\n");
      out.write("\t\tdisplay: none;\r\n");
      out.write("\t\t/* Hide the carousel text when the screen is less than 600 pixels wide */\r\n");
      out.write("\t}\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/**/\r\n");
      out.write(".box-info.full {\r\n");
      out.write("\tpadding: 0px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".box-info:hover {\r\n");
      out.write("\tcolor: #393E48;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".box-info {\r\n");
      out.write("\tposition: relative;\r\n");
      out.write("\tpadding: 15px;\r\n");
      out.write("\tbackground: #fff;\r\n");
      out.write("\tcolor: #5b5b5b;\r\n");
      out.write("\tmargin-bottom: 20px;\r\n");
      out.write("\t-webkit-transition: All 0.4s ease;\r\n");
      out.write("\t-moz-transition: All 0.4s ease;\r\n");
      out.write("\t-o-transition: All 0.4s ease;\r\n");
      out.write("\tbackground: #FFFFFF;\r\n");
      out.write("\tmargin-top: 20px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".box-info .nav-tabs {\r\n");
      out.write("\tbackground: #1B1E24;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".box-info .nav-tabs  li.active  a, .box-info .nav-tabs  li.active  a:hover,\r\n");
      out.write("\t.box-info .nav-tabs  li.active  a:focus {\r\n");
      out.write("\tcursor: default;\r\n");
      out.write("\tborder-top: none;\r\n");
      out.write("\tborder-right: none;\r\n");
      out.write("\tborder-left: none;\r\n");
      out.write("\tborder-bottom: none;\r\n");
      out.write("\tbackground-color: #ffffff;\r\n");
      out.write("\tcolor: #1B1E24;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".box-info .nav-tabs  li.active  a i, .box-info .nav-tabs  li.active  a:hover i,\r\n");
      out.write("\t.box-info .nav-tabs  li.active  a:focus i {\r\n");
      out.write("\tcolor: #212121;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".box-info .nav-tabs  li  a i {\r\n");
      out.write("\tcolor: #fff;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".box-info.full .box-footer {\r\n");
      out.write("\tpadding: 20px 20px 15px 20px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".box-info .media-list {\r\n");
      out.write("\tmargin-top: 30px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".box-info .media-list .media {\r\n");
      out.write("\tpadding: 5px 20px;\r\n");
      out.write("\tborder-bottom: 1px solid #eaeaea;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".box-info .media-list .media .media-object {\r\n");
      out.write("\twidth: 50px;\r\n");
      out.write("}\r\n");
      out.write(".scroll-widget{\r\n");
      out.write("    overflow: hidden;\r\n");
      out.write("    width: auto;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("<body>\r\n");
      out.write('\r');
      out.write('\n');
 Member member = (Member)session.getAttribute("member"); 
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"ko\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"/tonight/css/bootstrap.min.css\">\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("\t.navbar {\r\n");
      out.write("\t\tbackground-color: transparent;\r\n");
      out.write("\t\tborder-color: transparent;\r\n");
      out.write("\t}\r\n");
      out.write("\t.navbar:hover {\r\n");
      out.write("\t\tbackground-color: black !important;\r\n");
      out.write("\t}\r\n");
      out.write("\t.navbar a {\r\n");
      out.write("\t    color: white !important;\r\n");
      out.write("\t}\r\n");
      out.write("\t.navbar a:hover { color: red !important; }\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t@media (min-width: 768px) {\r\n");
      out.write("\t  .navbar-nav.navbar-center {\r\n");
      out.write("\t    position: absolute;\r\n");
      out.write("\t    left: 50%;\r\n");
      out.write("\t    transform: translatex(-50%);\r\n");
      out.write("\t  }\r\n");
      out.write("\t  #mobile-logo {\r\n");
      out.write("\t  \tdisplay: none !important;\r\n");
      out.write("\t  \tvisibility: hidden !important;\r\n");
      out.write("\t  }\r\n");
      out.write("\t}\r\n");
      out.write("\t@media (max-width: 767px) {\r\n");
      out.write("\t  #logo {\r\n");
      out.write("\t  \tdisplay: none !important;\r\n");
      out.write("\t  \tvisibility: hidden !important;\r\n");
      out.write("\t  }\r\n");
      out.write("\t  \r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<nav class=\"navbar navbar-default navbar-fixed-top\">\r\n");
      out.write("  <div class=\"container-fluid\">\r\n");
      out.write("    <div class=\"navbar-header\">\r\n");
      out.write("      <button type=\"button\" class=\"navbar-toggle\" data-toggle=\"collapse\" data-target=\".navbar-collapse\">\r\n");
      out.write("        <span class=\"icon-bar\"></span>\r\n");
      out.write("        <span class=\"icon-bar\"></span>\r\n");
      out.write("        <span class=\"icon-bar\"></span>                        \r\n");
      out.write("      </button>\r\n");
      out.write("      <a class=\"navbar-brand\" id=\"mobile-logo\"href=\"/tonight/index.jsp\"><img width=\"30\" src=\"/tonight/img/logo.png\"></a>\r\n");
      out.write("    </div>\r\n");
      out.write("    \r\n");
      out.write("    <div class=\"collapse navbar-collapse\">\r\n");
      out.write("      <ul class=\"nav navbar-nav navbar-center\">\r\n");
      out.write("        <li><a href=\"#\">인기</a></li>\r\n");
      out.write("        <li><a href=\"/tonight/tlist\">여행&nbsp;&nbsp;&nbsp;&nbsp;</a></li>\r\n");
      out.write("        <li><a id=\"logo\" class=\"navbar-brand\" href=\"/tonight/index.jsp\"><img width=\"65\" src=\"/tonight/img/logo.png\"></a>\r\n");
      out.write("        <li><a href=\"/tonight/alist\">숙소</a></li>\r\n");
      out.write("        <li><a href=\"/tonight/views/customerservice/serviceListView.jsp\">고객센터</a></li>\r\n");
      out.write("      </ul>\r\n");
      out.write("      <ul class=\"nav navbar-nav navbar-right\">\r\n");
      out.write("      \t");
 if(member == null) { 
      out.write("\r\n");
      out.write("        \t<li><a href=\"/tonight/views/member/loginForm.jsp\">로그인&nbsp;&nbsp;</a></li>\r\n");
      out.write("        ");
 } else { 
      out.write("\r\n");
      out.write("        \t<li><a href=\"minfo?memberid=");
      out.print( member.getMemberId() );
      out.write("\">마이페이지</a></li>\r\n");
      out.write("        \t<li><a href=\"/tonight/logout\">로그아웃&nbsp;&nbsp;</a></li>\r\n");
      out.write("        ");
 } 
      out.write("\r\n");
      out.write("        </ul>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("</nav>\r\n");
      out.write("<div id=\"startchange\"></div>\r\n");
      out.write("\r\n");
      out.write("<script src=\"/tonight/js/jquery-3.2.1.min.js\"></script>\r\n");
      out.write("<script src=\"/tonight/js/bootstrap.min.js\"></script>\r\n");
      out.write("<script>\r\n");
      out.write("\t$(function(){\r\n");
      out.write("\t\tvar scroll_start = 0;\r\n");
      out.write("\t\tvar startchange = $('#startchange');\r\n");
      out.write("\t\tvar offset = startchange.offset();\r\n");
      out.write("\r\n");
      out.write("\t\tif (startchange.length){\r\n");
      out.write("\t\t\t$(document).scroll(function() { \r\n");
      out.write("\t\t\t\tscroll_start = $(this).scrollTop();\r\n");
      out.write("\t\t\t\tif(scroll_start > offset.top) {\r\n");
      out.write("\t\t\t\t\t$('.navbar').css('background-color', 'rgba(0, 0, 0, 0.7)');\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\telse {\r\n");
      out.write("\t\t\t\t\t$('.navbar').css('background-color', 'transparent');\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t}\r\n");
      out.write("\t});\r\n");
      out.write("</script>\r\n");
      out.write("<script src=\"/tonight/js/jquery-3.2.1.min.js\"></script>\r\n");
      out.write("<script src=\"/tonight/js/bootstrap.min.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("<div class=\"jumbotron\">\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("\t<div class=\"container\" id=\"toTop\">\r\n");
      out.write("\t\t<h3 class=\"text-center\">");
      out.print(tour.getTourTitle());
      out.write("</h3>\r\n");
      out.write("\t\t<br>\r\n");
      out.write("\t\t<div class=\"row\">\r\n");
      out.write("\t\r\n");
      out.write("\t\t\t<div id=\"myCarousel\" class=\"carousel slide col-md-8\"\r\n");
      out.write("\t\t\t\tdata-ride=\"carousel\">\r\n");
      out.write("\t\t\t\t<!-- Indicators -->\r\n");
      out.write("\t\t\t\t<ol class=\"carousel-indicators\">\r\n");
      out.write("\t\t\t\t\t<li data-target=\"#myCarousel\" data-slide-to=\"0\" class=\"active\"></li>\r\n");
      out.write("\t\t\t\t\t<li data-target=\"#myCarousel\" data-slide-to=\"1\"></li>\r\n");
      out.write("\t\t\t\t\t<li data-target=\"#myCarousel\" data-slide-to=\"2\"></li>\r\n");
      out.write("\t\t\t\t</ol>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<!-- Wrapper for slides -->\r\n");
      out.write("\t\t\t\t<div class=\"carousel-inner\">\r\n");
      out.write("\t\t\t\t\t<div class=\"item active\">\r\n");
      out.write("\t\t\t\t\t\t<img src=\"/tonight/uploadfiles/la.jpg\" alt=\"Los Angeles\"\r\n");
      out.write("\t\t\t\t\t\t\tstyle=\"width: 100%;\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"carousel-caption\">\r\n");
      out.write("\t\t\t\t\t\t\t<h3>New York</h3>\r\n");
      out.write("\t\t\t\t\t\t\t<p>The atmosphere in New York is lorem ipsum.</p>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<div class=\"item\">\r\n");
      out.write("\t\t\t\t\t\t<img src=\"/tonight/uploadfiles/chicago.jpg\" alt=\"Chicago\"\r\n");
      out.write("\t\t\t\t\t\t\tstyle=\"width: 100%;\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"carousel-caption\">\r\n");
      out.write("\t\t\t\t\t\t\t<h3>Chicago</h3>\r\n");
      out.write("\t\t\t\t\t\t\t<p>Thank you, Chicago - A night we won't forget.</p>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<div class=\"item\">\r\n");
      out.write("\t\t\t\t\t\t<img src=\"/tonight/uploadfiles/ny.jpg\" alt=\"New york\"\r\n");
      out.write("\t\t\t\t\t\t\tstyle=\"width: 100%;\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"carousel-caption\">\r\n");
      out.write("\t\t\t\t\t\t\t<h3>LA</h3>\r\n");
      out.write("\t\t\t\t\t\t\t<p>Even though the traffic was a mess, we had the best time\r\n");
      out.write("\t\t\t\t\t\t\t\tplaying at Venice Beach!</p>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<!-- Left and right controls -->\r\n");
      out.write("\t\t\t\t\t<a class=\"left carousel-control\" href=\"#myCarousel\"\r\n");
      out.write("\t\t\t\t\t\tdata-slide=\"prev\"> <span\r\n");
      out.write("\t\t\t\t\t\tclass=\"glyphicon glyphicon-chevron-left\"></span> <span\r\n");
      out.write("\t\t\t\t\t\tclass=\"sr-only\">Previous</span>\r\n");
      out.write("\t\t\t\t\t</a> <a class=\"right carousel-control\" href=\"#myCarousel\"\r\n");
      out.write("\t\t\t\t\t\tdata-slide=\"next\"> <span\r\n");
      out.write("\t\t\t\t\t\tclass=\"glyphicon glyphicon-chevron-right\"></span> <span\r\n");
      out.write("\t\t\t\t\t\tclass=\"sr-only\">Next</span>\r\n");
      out.write("\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"col-md-4\">\r\n");
      out.write("\t\t\t\t<hr>\r\n");
      out.write("\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t<div class=\"col-xs-4\">\r\n");
      out.write("\t\t\t\t\t\t<p>투어 소개</p>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"col-xs-8\">\r\n");
      out.write("\t\t\t\t\t\t<p>");
      out.print(tdetail.getTourIntro());
      out.write("</p>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<hr>\r\n");
      out.write("\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t<div class=\"col-xs-4\">\r\n");
      out.write("\t\t\t\t\t\t<p>투어 리스트</p>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"col-xs-8\">\r\n");
      out.write("\t\t\t\t\t\t<p>");
      out.print(tdetail.getTourList());
      out.write("</p>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<hr>\r\n");
      out.write("\t\t\t\t<div class=\"row\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<div class=\"col-xs-4\">\r\n");
      out.write("\t\t\t\t\t\t<a href=\"#\"> <img src=\"/tonight/uploadfiles/bandmember.jpg\"\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"img-circle person\" alt=\"Random Name\"></a>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"col-xs-8\">\r\n");
      out.write("\t\t\t\t\t\t<p></p>\r\n");
      out.write("\t\t\t\t\t\t<p>가이드 소개글 공간 입니다</p>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<hr>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div class=\"container\">\r\n");
      out.write("\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t<div class=\"col-md-8\">\r\n");
      out.write("\t\t\t\t<div class=\"panel panel-default\">\r\n");
      out.write("\t\t\t\t\t<div class=\"panel-heading\">달력 공간</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"panel-body\">\r\n");
      out.write("\t\t\t\t\t\t<img src=\"https://placehold.it/150x80?text=IMAGE\"\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"img-responsive\" style=\"width: 100%\" alt=\"Image\">\r\n");
      out.write("\t\t\t\t\t\t<h5>여행 가능 날짜</h5>\r\n");
      out.write("\t\t\t\t\t\t");
 for(TourConf tconf : tconfList) { 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<p>시작일: ");
      out.print( tconf.getStartDate() );
      out.write(", 도착일: ");
      out.print( tconf.getArriavlaDate() );
      out.write(", 성인금액:");
      out.print( tconf.getTourAdultPrice() );
      out.write(", 소인가격: ");
      out.print( tconf.getTourChildPrice() );
      out.write(" </p>\r\n");
      out.write("\t\t\t\t\t\t");
 } 
      out.write("\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"panel panel-default hidden-md hidden-lg\">\r\n");
      out.write("\t\t\t\t\t<div class=\"panel-heading\">선택 확인/예약 공간</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"panel-body\">\r\n");
      out.write("\t\t\t\t\t\t<img src=\"https://placehold.it/150x80?text=IMAGE\"\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"img-responsive\" style=\"width: 100%\" alt=\"Image\">\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"panel panel-default\">\r\n");
      out.write("\t\t\t\t\t<div class=\"panel-heading\">상세일정</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"panel-body\">\r\n");
      out.write("\t\t\t\t\t\t");
      out.print(tdetail.getTourSchedule());
      out.write("\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"panel panel-default\">\r\n");
      out.write("\t\t\t\t\t<div class=\"panel-heading\">포함내역</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"panel-body\">\r\n");
      out.write("\t\t\t\t\t\t");
      out.print(tdetail.getTourHistory());
      out.write("\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"panel panel-default\">\r\n");
      out.write("\t\t\t\t\t<div class=\"panel-heading\">옵션</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"panel-body\">\r\n");
      out.write("\t\t\t\t\t\t");
      out.print(tdetail.getTourOption());
      out.write("\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"panel panel-default\">\r\n");
      out.write("\t\t\t\t\t<div class=\"panel-heading\">환불/취소 정책</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"panel-body\">\r\n");
      out.write("\t\t\t\t\t\t");
      out.print(tdetail.getTourPolicy());
      out.write("\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"panel panel-default\">\r\n");
      out.write("\t\t\t\t\t<div class=\"panel-heading\">후기\r\n");
      out.write("\t\t\t\t\t\t");
 if(treviewList.size() > 0) {
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<p class=\"pull-right\">(");
      out.print( treviewList.size() );
      out.write(")</p>\r\n");
      out.write("\t\t\t\t\t\t\t<p class=\"pull-right\">");
      out.print( gradeAvg );
      out.write("</p>\r\n");
      out.write("\t\t\t\t\t\t\t<img src=\"/tonight/img/starGrade");
      out.print( Math.round(gradeAvg) );
      out.write(".png\" class=\"col-xs-3 pull-right\" style=\"margin-top:-10px\">\r\n");
      out.write("\t\t\t\t\t\t");
 } 
      out.write("\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"panel-body box-info\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<div class=\"tab-pane active animated fadeInRight\" id=\"comments\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"scroll-widget\">\r\n");
      out.write("\t\t\t\t\t\t\t<ul class=\"media-list\">\r\n");
      out.write("\t\t\t\t\t\t\t");
 if (treviewList.isEmpty()) {	
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<li class=\"media\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<p>후기가 없습니다.</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t");
 } else if(treviewList.size() < 4){ 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t");
 for (TourReview treview : treviewList) { 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li class=\"media\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<a class=\"pull-left\" href=\"#fakelink\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<img class=\"media-object\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tsrc=\"https://bootdey.com/img/Content/User_for_snippets.png\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\talt=\"Avatar\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"media-body\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<h4 class=\"media-heading\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<a href=\"#fakelink\">");
      out.print(treview.getTrWriterId() );
      out.write("</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<small>");
      out.print(treview.getTrDate() );
      out.write("</small>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</h4>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<img src=\"/tonight/img/starGrade");
      out.print( Math.round(treview.getTrGrade()) );
      out.write(".png\" class=\"col-xs-3\" style=\"margin-top:-10px\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"col-xs-9\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<p>");
      out.print(treview.getTrContent() );
      out.write("</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<p></p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t");
 } 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t");
 } else {
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t");
 for (int i=0; i < 3; i++) { 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li class=\"media\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<a class=\"pull-left\" href=\"#fakelink\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<img class=\"media-object\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tsrc=\"https://bootdey.com/img/Content/User_for_snippets.png\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\talt=\"Avatar\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"media-body\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<h4 class=\"media-heading\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<a href=\"#fakelink\">");
      out.print( treviewList.get(i).getTrWriterId() );
      out.write("</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<small>");
      out.print(treviewList.get(i).getTrDate() );
      out.write("</small>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<small>grade ");
      out.print(treviewList.get(i).getTrGrade() );
      out.write("</small>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</h4>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<img src=\"/tonight/img/starGrade");
      out.print( Math.round(treviewList.get(i).getTrGrade()) );
      out.write(".png\" class=\"col-xs-3\" style=\"margin-top:-10px\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"col-xs-9\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<p>");
      out.print( treviewList.get(i).getTrContent() );
      out.write("</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t");
 } 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<li class=\"media\"><a data-toggle=\"modal\" data-target=\"#addReview\">");
      out.print( treviewList.size()-3 );
      out.write("개 더보기..</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t");
 } 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<div class=\"col-md-4 hidden-sm hidden-xs\">\r\n");
      out.write("\t\t\t\t<div class=\"panel panel-default panel-affix\" id=\"myScrollspy\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<div class=\"panel-heading\">결제 공간</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"panel-body\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"nav nav-pills nav-stacked\">\r\n");
      out.write("\t\t\t\t\t\t\t<img src=\"https://placehold.it/150x80?text=IMAGE\"\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"img-responsive\" style=\"width: 100%\" alt=\"Image\"> <a\r\n");
      out.write("\t\t\t\t\t\t\t\thref=\"#toTop\">Back To Top </a>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("<div class=\"modal fade\" id=\"addReview\" role=\"dialog\">\r\n");
      out.write("    <div class=\"modal-dialog\">\r\n");
      out.write("    \r\n");
      out.write("      <!-- Modal content-->\r\n");
      out.write("      <div class=\"modal-content\">\r\n");
      out.write("        <div class=\"modal-header\">\r\n");
      out.write("        <button type=\"button\" class=\"close\" data-dismiss=\"modal\">&times;</button>\r\n");
      out.write("          <h4 class=\"modal-title\">후기</h4>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"modal-body box-info\">\r\n");
      out.write("        \t<div class=\"tab-pane active animated fadeInRight\" id=\"comments\">\r\n");
      out.write("\t\t\t\t<div class=\"scroll-widget\">\r\n");
      out.write("\t\t\t\t\t<ul class=\"media-list\">\r\n");
      out.write("\t\t\t\t\t\t");
 for (TourReview treview : treviewList) { 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<li class=\"media\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<a class=\"pull-left\" href=\"#fakelink\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<img class=\"media-object\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tsrc=\"https://bootdey.com/img/Content/User_for_snippets.png\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\talt=\"Avatar\">\r\n");
      out.write("\t\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"media-body\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<h4 class=\"media-heading\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<a href=\"#fakelink\">");
      out.print(treview.getTrWriterId() );
      out.write("</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<small>");
      out.print(treview.getTrDate() );
      out.write("</small>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</h4>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<img src=\"/tonight/img/starGrade");
      out.print( Math.round(treview.getTrGrade()) );
      out.write(".png\" class=\"col-xs-3\" style=\"margin-top:-10px\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"col-xs-9\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<p>");
      out.print(treview.getTrContent() );
      out.write("</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<p></p>\r\n");
      out.write("\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t");
 } 
      out.write("\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("        </div>\r\n");
      out.write("\t        <div class=\"modal-footer\">\r\n");
      out.write("\t\t\t\t<button type=\"button\" class=\"btn btn-default\" data-dismiss=\"modal\">닫기</button>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("      \r\n");
      out.write("\t</div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<div id=\"fake-footer\"></div>\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"/tonight/css/style.css\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<footer class=\"container-fluid text-center\">\r\n");
      out.write("\t<address>tonight</address>\r\n");
      out.write("\t<small>ⓒ  Gangnam Station Exit 10</small>\r\n");
      out.write("</footer>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("<script src=\"/tonight/js/jquery-3.2.1.min.js\"></script>\r\n");
      out.write("<script src=\"/tonight/js/bootstrap.min.js\"></script>\r\n");
      out.write("<script>\r\n");
      out.write("\t$(function() {\r\n");
      out.write("\r\n");
      out.write("\t\t// name your elements here\r\n");
      out.write("\t\tvar stickyElement = '.panel-affix', // the element you want to make sticky\r\n");
      out.write("\t\tbottomElement = '#fake-footer'; // the bottom element where you want the sticky element to stop (usually the footer) \r\n");
      out.write("\r\n");
      out.write("\t\t// make sure the element exists on the page before trying to initalize\r\n");
      out.write("\t\tif ($(stickyElement).length) {\r\n");
      out.write("\t\t\t$(stickyElement).each(\r\n");
      out.write("\t\t\t\tfunction() {\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t// let's save some messy code in clean variables\r\n");
      out.write("\t\t\t\t\t// when should we start affixing? (the amount of pixels to the top from the element)\r\n");
      out.write("\t\t\t\t\tvar fromTop = $(this).offset().top,\r\n");
      out.write("\t\t\t\t\t// where is the bottom of the element?\r\n");
      out.write("\t\t\t\t\tfromBottom = $(document).height()\r\n");
      out.write("\t\t\t\t\t\t\t- ($(this).offset().top + $(this)\r\n");
      out.write("\t\t\t\t\t\t\t\t\t.outerHeight()),\r\n");
      out.write("\t\t\t\t\t// where should we stop? (the amount of pixels from the top where the bottom element is)\r\n");
      out.write("\t\t\t\t\t// also add the outer height mismatch to the height of the element to account for padding and borders\r\n");
      out.write("\t\t\t\t\tstopOn = $(document).height()\r\n");
      out.write("\t\t\t\t\t\t\t- ($(bottomElement).offset().top)\r\n");
      out.write("\t\t\t\t\t\t\t+ ($(this).outerHeight() - $(this)\r\n");
      out.write("\t\t\t\t\t\t\t\t\t.height());\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t// if the element doesn't need to get sticky, then skip it so it won't mess up your layout\r\n");
      out.write("\t\t\t\t\tif ((fromBottom - stopOn) > 200) {\r\n");
      out.write("\t\t\t\t\t\t// let's put a sticky width on the element and assign it to the top\r\n");
      out.write("\t\t\t\t\t\t$(this).css('width', $(this).width())\r\n");
      out.write("\t\t\t\t\t\t\t\t.css('top', 0).css('position',\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t'');\r\n");
      out.write("\t\t\t\t\t\t// assign the affix to the element\r\n");
      out.write("\t\t\t\t\t\t$(this)\r\n");
      out.write("\t\t\t\t\t\t\t\t.affix({\r\n");
      out.write("\t\t\t\t\t\t\t\t\toffset : {\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t// make it stick where the top pixel of the element is\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\ttop : fromTop - 80,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t// make it stop where the top pixel of the bottom element is\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tbottom : stopOn\r\n");
      out.write("\t\t\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t\t// when the affix get's called then make sure the position is the default (fixed) and it's at the top\r\n");
      out.write("\t\t\t\t\t\t\t\t})\r\n");
      out.write("\t\t\t\t\t\t\t\t.on(\r\n");
      out.write("\t\t\t\t\t\t\t\t\t'affix.bs.affix',\r\n");
      out.write("\t\t\t\t\t\t\t\t\tfunction() {\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t$(this)\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t.css('top',\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t'80px')\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t.css(\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t'position',\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t'');\r\n");
      out.write("\t\t\t\t\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t// trigger the scroll event so it always activates \r\n");
      out.write("\t\t\t\t\t$(window).trigger('scroll');\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write("\t});\r\n");
      out.write("</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
